version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sales-dashboard-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/sales_dashboard
      - JWT_SECRET=your_secure_jwt_secret
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - sales-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sales-dashboard-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sales-network

  mongo:
    image: mongo:6.0
    container_name: sales-db
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    ports:
      - "27017:27017"
    networks:
      - sales-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=securepassword
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge

volumes:
  mongodb_data:
